export enum COUNTER {
  INCREMENT = 'COUNTER:INCREMENT',
  DECREMENT = 'COUNTER:DECREMENT',
  IS_LOADING = 'COUNTER:IS_LOADING',
}

export enum MOVIES {
  GET_LIST_MOVIES = 'MOVIES:GET_LIST_MOVIES',
}

export enum CONVERSION {
  SET_SOURCE_CURRENCY = 'CONVERSION:SET_SOURCE_CURRENCY',
  SET_DESTINATION_CURRENCY = 'CONVERSION:SET_DESTINATION_CURRENCY',
  SET_AMOUNT = 'CONVERSION:SET_AMOUNT',
  SET_SOURCE_CURRENCIES = 'CONVERSION:SET_SOURCE_CURRENCIES',
  SET_DESTINATION_CURRENCIES = 'CONVERSION:SET_DESTINATION_CURRENCIES',
  SET_LIVE_EXCHANGE_RATE = 'CONVERSION:SET_LIVE_EXCHANGE_RATE',
  ADD_TO_HISTORY = 'CONVERSION:ADD_TO_HISTORY',
  SET_IS_LOADING = 'CONVERSION:SET_IS_LOADING',
}

export enum EXPENSES {
  SET_ITEMS = 'EXPENSES:SET_ITEMS',
  ADD_ITEM = 'EXPENSES:ADD_ITEM',
  REMOVE_ITEM = 'EXPENSES:REMOVE_ITEM',
}

export enum CREDIT_SCORE {
  SET_DASHBOARD = 'CREDIT_SCORE:SET_DASHBOARD',
}

export enum GOALS {
  SET_ITEMS = 'GOALS:SET_ITEMS',
  UPSERT_ITEM = 'GOALS:UPSERT_ITEM',
  REMOVE_ITEM = 'GOALS:REMOVE_ITEM',
}
