export enum CONVERSATION {
  SET_LOAD_STATUS = 'CONVERSATION:SET_LOAD_STATUS',
  SET_MESSAGES = 'CONVERSATION:SET_MESSAGES',
  ADD_MESSAGE = 'CONVERSATION:ADD_MESSAGE',
  PATCH_MESSAGE = 'CONVERSATION:PATCH_MESSAGE',
  REMOVE_MESSAGE = 'CONVERSATION:REMOVE_MESSAGE',
  SET_REPLY = 'CONVERSATION:SET_REPLY',
}
